### ISSUE TITLE
Making dependencies optional

### ISSUE THREAD

**Issue by kabergstrom** [zshipko/image2-rs#3]
Great crate, thank you so much!

I was combing through my dependency tree and found that image2 is non-optionally pulling in `rayon`, all of `futures`, and a few other crates. Do you think it would be possible to make some of this optional, and use as few features of dependencies of larger crates like `futures`  as needed by `image2`?

**Comment by zshipko** [comment]
Hey, I am in the process of rewriting image2 to use https://github.com/OpenImageIO/oiio because it has support for a few different formats I’m interested in. That is quite a big dependency, but is typically available on the package manager provided by your OS. 

I will definitely make rayon and futures optional, but just wanted to give you a warning about the oiio dependency. 

Edit: I suppose I could also make that optional and leave the ImageMagick reader/writer which uses no external dependencies (other than the ImageMagick executable)

**Comment by zshipko** [comment]
Just made this commit: https://github.com/zshipko/image2-rs/commit/731a2c4d029cec2fab343d543669e7ba4677b879 to enable building with almost no dependencies (using imagemagick as the backend)  by using `--no-default-features` - let me know if you have any issues with that.

Are you using the `Image` trait? I found it to be overkill and have converted it to a struct in the rewrite. This makes things a little simpler - but I could figure something out if you still need that to be a trait.
